### PR TITLE
Improve Logo customization

### PR DESCRIPTION
**Pull request by m4lt3**
The user can now more easily add their own logo via a simple file upload form. They can also decide which dimension of the logo they want to resize.
If the logo is the only element in the branding block, its width can be up to 100%, otherwise only 50% to leave space for the text.

### CODE REVIEW

**Comment by danzinger** [comment]
Looks perfect👍 This was really needed. Thank you very much for contributing to this project! I will merge the changes into the master branch soon and release the update.

**Comment by m4lt3** [comment]
I'm always happy to help! I'm currently extending your theme for my university, so I work a lot with it. I could also offer to add multilanguage / simplesearch support if you'd like to. It's mostly a matter of copy/paste.

You can checkout what I mean at https://fbe-cloud.rwu.de/nachhaltigkeit/~test

**Comment by danzinger** [comment]
Sorry for answering late, i've been so busy in my day job. Wow, its amazing to see what you've built on top of Vela! This could actually be released as a new theme...

My goal with the Vela theme was always to keep it simple and clean. Both the code and the frontend. I tried to provide a theme for anybody who simply needs to present large amounts of content in a structured way that works perfectly on all devices and browsers (I teach math classes and use this theme to provide learning videos and other materials to students).

If you run the Lighthouse audit in Chrome there are still some things missing for 100% rating (Font loading, ...) Also the theme needs updates to load assets "deferred" as it's now recommended to do this to ensure plugin compatibility: https://getgrav.org/blog/important-theme-updates 

So the first things on my list are more on the technical side. I really dislike the font-flickering in the menu, when a new page is loaded. There is a small moment there you see no fonts. This would be also cool to be fixed for example.

**Comment by m4lt3** [comment]
No problem, you are doing this in your free time and there are way more important things in life than this theme.

Thank you for your kind works and recommendations. 

I did not plan to force all my changes onto your theme, which clearly fulfills all goals you have set, I simply wanted to present the multi-language support, as this is hard to describe.

**Pull request merged**
